//created on: 2018-11-28
package com.gr.tfnick

import com.tfnick.demo.facts.PersonModel;



rule "IV011-申请次数超过3次转人工"
    no-loop true
    ruleflow-group "demo_rules2"
    when
        m:PersonModel(count > 3 && count < 5)
    then
        System.out.println("IV011");
        m.setAdvice("cancel");
        m.setReason("申请次数超过3次转人工");
        update(m);

end

rule "IV021-申请次数过多拒绝"
    no-loop true
    ruleflow-group "demo_rules2"
    when
        m:PersonModel(count >= 5)
    then
        System.out.println("IV021");
        m.setAdvice("reject");
        m.setReason("申请次数过多拒绝");
        update(m);

end
