//created on: 2018-11-28
package com.gr.tfnick

//list any import classes here.
import com.tfnick.demo.facts.PersonModel;


//declare any global variables here
rule "AC00-核心数据缺失不贷"
    no-loop true
    ruleflow-group "rf-group"
    when
        m:PersonModel(province == null || age == null)
    then
        System.out.println("AC00");
        m.setAdvice("reject");
        m.setReason("核心数据不足不贷");
        update(m);

end



rule "AC01-北上广超过30的成年人不贷"
    no-loop true
    ruleflow-group "rf-group"
    when
        m:PersonModel(province in ("北京","上海","深圳"), age < 18 || age > 30)
    then
        System.out.println("AC01");
        m.setAdvice("reject");
        m.setReason("北上广超过30的成年人不贷");
        update(m);

end

rule "AC02-其他省份年龄高于50的不贷"
    no-loop true
    ruleflow-group "rf-group"
    when
        m:PersonModel(province not in ("北京","上海","深圳"), age < 18 || age > 50)
    then
        System.out.println("AC02");
        m.setAdvice("reject");
        m.setReason("其他省份年龄高于50的不贷");
        update(m);

end
