//created on: 2018-11-28
package com.gr.tfnick

//list any import classes here.
import com.tfnick.demo.facts.PersonModel;


//declare any global variables here
rule "AC00-核心数据缺失不贷"
    lock-on-active true
    ruleflow-group "demo_rules1"
    when
        m:PersonModel(province == null || age == null)
    then
        System.out.println("AC00");
        m.setAdvice("reject");
        m.setReason("核心数据不足不贷");
        update(m);

end



rule "AC01-北上广超过30的成年人不贷"
    lock-on-active true
    ruleflow-group "demo_rules1"
    when
        m:PersonModel(province in ("BJ","SH","SZ"),  age > 30)
    then
        System.out.println("AC01");
        m.setAdvice("reject");
        m.setReason("北上广超过30的成年人不贷");
        update(m);

end

rule "AC02-其他省份年龄高于50的不贷"
    lock-on-active true
    ruleflow-group "demo_rules1"
    when
        m:PersonModel(province not in ("BJ","SH","SZ"),  age > 50)
    then
        System.out.println("AC02");
        m.setAdvice("reject");
        m.setReason("其他省份年龄高于50的不贷");
        update(m);

end


rule "AC03-未成年人不贷"
    lock-on-active true
    ruleflow-group "demo_rules2"
    when
        m:PersonModel(age < 18)
    then
        System.out.println("AC03");
        m.setAdvice("reject");
        m.setReason("未成年人不贷");
        update(m);

end

/*


rule "IV02-申请次数过多拒绝"
    lock-on-active true
    ruleflow-group "demo_rules2"
    when
        m:PersonModel(count > 2)
    then
        System.out.println("IV02");
        m.setAdvice("reject");
        m.setReason("申请次数过多拒绝");
        update(m);

end

*/

